"use client";
import {useEffect,useRef,useState} from "react";
import styles from "./FinanceCashFlow.module.css";
const money=v=>v==null?"Not available":new Intl.NumberFormat("en-PH",{style:"currency",currency:"PHP"}).format(Number(v));
const today=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Manila",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
export default function FinanceCashCollections({rows,accounts,transactions,period,busy,error,onSave}){
 const [store,setStore]=useState(""),[selected,setSelected]=useState(null),[draft,setDraft]=useState({}),[request,setRequest]=useState(null);
 const form=useRef(null);
 useEffect(()=>{if(selected){form.current?.scrollIntoView({behavior:"smooth",block:"center"});form.current?.querySelector("select")?.focus({preventScroll:true});}},[selected]);
 const shown=rows.filter(r=>(!store||r.store_id===store)&&(r.business_date>=period.from||Number(r.remaining)>0));
 const stores=[...new Map(rows.map(r=>[r.store_id,r.store_name])).entries()];
 function open(row){setSelected(row);setDraft({transaction_date:today(),amount:String(Math.max(0,Number(row.remaining))),fee:"0",to_account_id:"",reference:"",notes:"",transaction_id:""});setRequest(null);}
 function change(key,value){setDraft(d=>({...d,[key]:value}));setRequest(null);}
 return <section className={styles.panel}><h2>Daily Cash Collection</h2>
  <p className={styles.help}>Monitor cash sales and movement of the declared cash. Cash available for transfer = declared cash − initial fund. Final End Day counts take priority; otherwise the latest closed-shift count is provisional. Closed-shift cash sales exclude refunds and count each captured receipt once.</p>
  <p className={styles.help}>Counts are monitoring records and do not add cash to the ledger. Record Cash In under Record Movement before transferring funds if it has not already been recorded. Link an existing transfer to avoid posting it twice.</p>
  <label className={styles.field}>Store<select value={store} onChange={e=>setStore(e.target.value)}><option value="">All stores</option>{stores.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>
  <div className={styles.scroll}><table><thead><tr><th>Date</th><th>Store</th><th>Cash sales</th><th>Declared cash</th><th>Initial fund</th><th>Declared less initial</th><th>Difference vs sales</th><th>Transferred (gross)</th><th>Awaiting transfer</th><th>Count basis</th><th>Action</th></tr></thead><tbody>{shown.map(r=><tr key={`${r.store_id}-${r.business_date}`}><td>{r.business_date}</td><td>{r.store_name}</td><td>{money(r.cash_sales)}</td><td>{money(r.declared_cash)}</td><td>{money(r.initial_fund)}</td><td>{money(r.net_declared)}</td><td>{money(r.variance)}</td><td>{money(r.transferred)}</td><td>{money(r.remaining)}</td><td>{r.count_basis==="end_day"?"End Day":"Latest shift · provisional"}</td><td><button type="button" disabled={busy||r.net_declared==null||Number(r.remaining)<=0} onClick={()=>open(r)}>Record / Link Transfer</button></td></tr>)}</tbody></table></div>
  {!shown.length&&<p>No closed-shift cash collection records for this selection.</p>}
  {selected&&<form ref={form} onSubmit={e=>{e.preventDefault();const id=request||crypto.randomUUID();setRequest(id);onSave("finance_cash_sales_transfer",{p_data:{...draft,request_id:id,store_id:selected.store_id,business_date:selected.business_date}},"Cash sales transfer recorded.",()=>setSelected(null));}}><h3>Cash sales transfer — {selected.store_name} · {selected.business_date}</h3>{error&&<p role="alert" className={styles.error}>{error}</p>}<fieldset disabled={busy} className={styles.form}>
   <label className={styles.field}>Existing transfer (optional)<select value={draft.transaction_id} onChange={e=>change("transaction_id",e.target.value)}><option value="">Post a new transfer</option>{transactions.filter(t=>t.kind==="transfer"&&!t.reversed&&t.from_account_id===selected.source_account_id&&t.transaction_date>=selected.business_date).map(t=><option key={t.id} value={t.id}>{t.transaction_date} · {t.reference} · {money(t.amount)}</option>)}</select></label>
   {!draft.transaction_id&&<><label className={styles.field}>Transfer date<input type="date" required min={selected.business_date} value={draft.transaction_date} onChange={e=>change("transaction_date",e.target.value)}/></label><label className={styles.field}>Receiving fund source<select required value={draft.to_account_id} onChange={e=>change("to_account_id",e.target.value)}><option value="">Select receiving account</option>{accounts.filter(a=>a.id!==selected.source_account_id).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label className={styles.field}>Gross amount sent<input type="number" required min="0.01" max={selected.remaining} step="0.01" value={draft.amount} onChange={e=>change("amount",e.target.value)}/></label><label className={styles.field}>Transfer fees<input type="number" required min="0" max={Math.max(0,Number(draft.amount)-0.01)} step="0.01" value={draft.fee} onChange={e=>change("fee",e.target.value)}/></label><label className={styles.field}>Transfer reference<input required value={draft.reference} onChange={e=>change("reference",e.target.value)}/></label><label className={styles.field}>Notes<input value={draft.notes} onChange={e=>change("notes",e.target.value)}/></label></>}
   <p className={styles.help}>Sending account: {accounts.find(a=>a.id===selected.source_account_id)?.name||"Missing branch petty cash account"}. Pending: {money(selected.remaining)}. New transfers also appear in Cash Ledger and update petty cash. Existing transfers are linked without another cash movement.</p><button disabled={!selected.source_account_id}>{draft.transaction_id?"Link Transfer":"Post Transfer"}</button><button type="button" onClick={()=>setSelected(null)}>Cancel</button>
  </fieldset></form>}
  <h3>Cash sales transfer history</h3><div className={styles.scroll}><table><thead><tr><th>Sales date</th><th>Store</th><th>Transfer date</th><th>Receiving fund</th><th>Gross sent</th><th>Fees</th><th>Reference</th><th>Type</th></tr></thead><tbody>{shown.flatMap(r=>(r.history||[]).map(t=><tr key={t.id}><td>{r.business_date}</td><td>{r.store_name}</td><td>{t.date}</td><td>{t.receiving_account}</td><td>{money(t.amount)}</td><td>{money(t.fee)}</td><td>{t.reference}</td><td>{t.kind}</td></tr>))}</tbody></table></div>
 </section>;
}
